name: ck_linecode
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  fl_chart: ^0.62.0
  shimmer: ^2.0.0
  webview_flutter: ^4.2.1
  # file_picker: ^5.3.2
  file_picker: '>=5.3.0 <5.3.2'
  image_picker: ^0.8.7+5
  image: ^4.0.17
  path_provider: ^2.0.15
  intl: ^0.18.1
  http: ^1.1.0
  args: ^2.4.2
  device_preview: ^1.1.0
  rxdart: ^0.27.7
  collection: ^1.17.2
  percent_indicator: ^4.2.3
  # path_provider_windows: ^2.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
