name: Post to X
on: [push]
#   push:
#     branches:
#     - main
jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - uses: devigned/go-twitter-action@v1
        with:
          message: "CK line updated!"
          apiKey: ${{ secrets.TWITTER_CONSUMER_KEY }}
          apiKeySecret: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          accessToken: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          accessTokenSecret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
      # - uses: dart-actions/tweet@v1.0.0
      #   with:
      #     text: "CK Line repo updated!"
      #     bearer-token: ${{ secrets.TWITTER_BEARER_TOKEN }}
      #     # consumer-key: ${{ secrets.TWITTER_CONSUMER_KEY }}
      #     # consumer-secret: ${{ secrets.TWITTER_CONSUMER_SECRET }}
      #     access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      #     access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
