name: Post to X
on: 
  [push]
#   push:
#     branches:
#     - main
jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - uses: dart-actions/tweet@v1.0.1
        with:
          text: "CK Line repo updated!"
          bearer-token: ${{ secrets.TWITTER_BEARER_TOKEN }}